### ISSUE TITLE
help me

### ISSUE THREAD

**Issue by holograman** [igbt6/WebBots#1]
How do I send a message? and comment?

**Comment by luk6xff** [comment]
@holograman - Hello what do you want konow or how can i help : ) ?   Write a comment below or private msg via email to: lukasz.uszko@gmail.com  Regards!

**Comment by holograman** [comment]
hi thank for reply.

I have made the necessary settings and the program is running but not sending any messages

**Comment by luk6xff** [comment]
which program you are talking about ?

**Comment by holograman** [comment]
interpals bot.

**Comment by luk6xff** [comment]
Yeah, there was a small change on the website. I have updated the code at the moment, please use the updated version. Regards!

**Comment by luk6xff** [comment]
One important thing, please do not use the bot for sending spam or other junk messages! you will be deleted from the interpals in such case

**Comment by holograman** [comment]
Thank you so much . :) 
How will I use it?

**Comment by luk6xff** [comment]
as stated in usage section.

**Comment by luk6xff** [comment]
bot.sendMessage("UserWeirdName","Hi!")          #send message "Hi!" to a user UserWeirdName

**Comment by holograman** [comment]
:( dont work. Incorrect age value 16 100 allowed

**Comment by luk6xff** [comment]
It does work, show me your script hoy you use it ?

**Comment by holograman** [comment]
Ok come to mail.

**Comment by luk6xff** [comment]
ok, waiting

**Comment by holograman** [comment]
ım send pls check

**Comment by holograman** [comment]
not pratic bot :)
